# Generated by Django 3.2.5 on 2021-07-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotodummy',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stage_type', models.CharField(choices=[('Child', 'CHILD'), ('Teen', 'TEEN'), ('Pensioner', 'PENSIONER'), ('Graduated', 'GRADUATED')], max_length=20)),
                ('rarity_type', models.CharField(blank=True, choices=[('Rare', 'RARE'), ('Very Rare', 'VERY RARE'), ('Super Rare', 'SUPER RARE'), ('Ultra Rare', 'ULTRA RARE')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('stage_type', models.CharField(blank=True, choices=[('Child', 'CHILD'), ('Teen', 'TEEN'), ('Pensioner', 'PENSIONER'), ('Graduated', 'GRADUATED')], max_length=20)),
                ('password', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kotopedia.kotodummy')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(choices=[('Cheerful', 'CHEERFUL'), ('Cute', 'CUTE'), ('Dark', 'DARK'), ('Serious', 'SERIOUS'), ('Cool', 'COOL')], max_length=15)),
                ('kotodummy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kotopedia.kotodummy')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kotopedia.word')),
            ],
        ),
    ]
