# Generated by Django 3.2.5 on 2021-07-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0002_auto_20210720_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kotodummy',
            old_name='raritytype',
            new_name='rarity_type',
        ),
        migrations.RenameField(
            model_name='kotodummy',
            old_name='stagetype',
            new_name='stage_type',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='stage',
            new_name='stage_type',
        ),
    ]
