# Generated by Django 3.2.5 on 2021-07-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0002_alter_kotodummy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotodummy',
            name='image',
            field=models.CharField(default='static/thumbs/<django.db.models.fields.IntegerField>_<django.db.models.fields.CharField>.jpg', max_length=50),
        ),
    ]
