# Generated by Django 3.2.5 on 2021-07-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0003_alter_kotodummy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotodummy',
            name='image',
        ),
    ]
