# Generated by Django 3.2.5 on 2021-07-20 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0003_auto_20210720_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kotopedia.kotodummy'),
        ),
    ]
