# Generated by Django 3.2.5 on 2021-07-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0004_word_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('Child', 'CHILD'), ('Teen', 'TEEN'), ('Pensioner', 'PENSIONER'), ('Graduated', 'GRADUATED')], max_length=20),
        ),
    ]
