# Generated by Django 3.2.5 on 2021-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0004_remove_kotodummy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotodummy',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
