# Generated by Django 3.2.5 on 2021-07-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0005_alter_word_stage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='kotodummy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kotopedia.kotodummy'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kotopedia.word'),
        ),
    ]
