# Generated by Django 3.2.5 on 2021-07-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0006_alter_kotodummy_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='password',
        ),
        migrations.AddField(
            model_name='kotodummy',
            name='password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kotopedia.word'),
        ),
    ]
