# Generated by Django 3.2.5 on 2021-07-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0007_auto_20210729_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotodummy',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
