# Generated by Django 3.2.5 on 2021-07-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0009_auto_20210730_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotodummy',
            name='password',
        ),
    ]
