# Generated by Django 3.2.5 on 2021-07-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0010_remove_kotodummy_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotodummy',
            name='password',
            field=models.ManyToManyField(blank=True, null=True, to='kotopedia.Word'),
        ),
    ]
