# Generated by Django 3.2.5 on 2021-07-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotopedia', '0014_word_kotodummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='kotodummy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kotopedia.kotodummy'),
        ),
    ]
